
DROP TABLE IF EXISTS PHARMACY_DETAILS;


CREATE TABLE IF NOT EXISTS PHARMACY_DETAILS (
    PHARMACY_MASTER_ID   VARCHAR2(12) NOT NULL,
    PHARMACY_NAME        VARCHAR2(100),
    IS_REGISTERED        VARCHAR2(1),
    ADDRESS_LINE         VARCHAR2(300),
    AREA                 VARCHAR2(100),
    CITY                 VARCHAR2(50),
    STATE                VARCHAR2(50),
    POSTAL_CODE          VARCHAR2(10),
    COUNTRY              VARCHAR2(30),
    LATITUDE             VARCHAR2(30),
    LONGITUDE            VARCHAR2(30),
    OPEN_TIME            VARCHAR2(10),
    CLOSED_TIME          VARCHAR2(10),
    PHONE                VARCHAR2(15),
    WEBSITE              VARCHAR2(50),
    CONSTRAINT PK_PHARMACY_DETAILS PRIMARY KEY (PHARMACY_MASTER_ID)
);



CREATE TABLE IF NOT EXISTS DRUG_DETAILS (
    DRUG_ID           VARCHAR2(12),
    DRUG_NAME         VARCHAR2(300),
    IS_ACTIVE         VARCHAR2(2),
    CONSTRAINT PK_DRUG_DETAILS PRIMARY KEY (DRUG_ID)
);

CREATE TABLE IF NOT EXISTS PHARMACY_DRUG_MASTER(
    MAPPING_ID			 VARCHAR2(12),
	PHARMACY_MASTER_ID   VARCHAR2(12),
	DRUG_ID              VARCHAR2(12),
	IS_AVAILABLE       	 VARCHAR2(2),
	DRUG_PRICE_EACH		 DOUBLE,
	CURRENCY			 VARCHAR2(10),
	CONSTRAINT PK_PHARMACY_DRUG_MASTER PRIMARY KEY (MAPPING_ID)
);