

CREATE TABLE PHARMACY_DETAILS(PHARMACY_MASTER_ID VARCHAR2(12) NOT NULL,PHARMACY_NAME VARCHAR2(50),ADDRESS_LINE_1 VARCHAR2(100),
CITY VARCHAR2(50), STATE VARCHAR2(50), POSTAL_CODE NUMBER, COUNTRY VARCHAR2(30),IS_REGISTERED VARCHAR2(1),PHARMACY_OPENS VARCHAR2(5),
PHARMACY_CLOSED VARCHAR2(5), PHONE VARCHAR2(15),WEBSITE VARCHAR2(50), CONSTRAINT PK_PHARMACY_DETAILS PRIMARY KEY(PHARMACY_MASTER_ID));