
INSERT INTO EMDRUGS VALUES (100,'RAM');
INSERT INTO EMDRUGS VALUES (200,'SAM');

INSERT INTO PHARMACY_DETAILS(PHARMACY_MASTER_ID,PHARMACY_NAME,ADDRESS_LINE_1,CITY,STATE,POSTAL_CODE,COUNTRY,IS_REGISTERED,PHARMACY_OPENS,
PHARMACY_CLOSED,PHONE,WEBSITE) VALUES('MST10001','APPOLO PHARMACY','NO-5, SHAKTHI STREET, DLF','CHENNAI','TAMILNADU','600087','INDIA','Y','9AM','9PM',
'044-2574164','WWW.APPOLODLF.COM');